"""added file_type to document model

Revision ID: 03d3e4df8dfd
Revises: 1449e1eb34ba
Create Date: 2026-03-27 15:55:30.728027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d3e4df8dfd'
down_revision: Union[str, Sequence[str], None] = '1449e1eb34ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
