"""add search_vector to documents

Revision ID: 0e8f331f6b9d
Revises: 03d3e4df8dfd
Create Date: 2026-04-01 00:26:49.631360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e8f331f6b9d'
down_revision: Union[str, Sequence[str], None] = '03d3e4df8dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'search_vector')
    # ### end Alembic commands ###
