"""add url_sources table

Revision ID: 297d0d810112
Revises: 4a7c8b9d3e2f
Create Date: 2026-04-27 08:46:21.888541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297d0d810112'
down_revision: Union[str, Sequence[str], None] = '4a7c8b9d3e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('scrape_status', sa.String(), nullable=True),
    sa.Column('next_scrape_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_url_sources_id'), 'url_sources', ['id'], unique=False)
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    op.alter_column('qa_history', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('qa_history', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_qa_history_id'), 'qa_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_history_id'), table_name='qa_history')
    op.alter_column('qa_history', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('qa_history', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('documents', 'source_url')
    op.drop_index(op.f('ix_url_sources_id'), table_name='url_sources')
    op.drop_table('url_sources')
    # ### end Alembic commands ###
