"""add ocr_confidence and image_path to document_chunks

Revision ID: 4a7c8b9d3e2f
Revises: 2e59aba6394d
Create Date: 2026-04-22 11:27:48.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7c8b9d3e2f'
down_revision: Union[str, Sequence[str], None] = '2e59aba6394d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('document_chunks')]
    if 'ocr_confidence' not in columns:
        op.add_column('document_chunks', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    if 'image_path' not in columns:
        op.add_column('document_chunks', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'image_path')
    op.drop_column('document_chunks', 'ocr_confidence')
    # ### end Alembic commands ###
