"""description

Revision ID: d164a3e87f00
Revises: 297d0d810112
Create Date: 2026-04-27 16:06:19.281543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd164a3e87f00'
down_revision: Union[str, Sequence[str], None] = '297d0d810112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_sources', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'url_sources', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_sources', type_='foreignkey')
    op.drop_column('url_sources', 'document_id')
    # ### end Alembic commands ###
